parameters:
    vairogs.utils.lexik.translation.crud.controller.class: Vairogs\Utils\Translatable\Controller\TranslationCRUDController
    vairogs.utils.lexik.translation.admin.orm.class: Vairogs\Utils\Translatable\Admin\ORMTranslationAdmin
    vairogs.utils.lexik.translation.admin.orm.entity: Lexik\Bundle\TranslationBundle\Entity\TransUnit
    vairogs.utils.lexik.translation.admin.orm.template: 'Lexik/CRUD/list.html.twig'

services:
    vairogs.utils.lexik.translation.crud.controller:
        class: '%vairogs.utils.lexik.translation.crud.controller.class%'
        public: true

    vairogs.utils.lexik.translation.admin.orm:
        class: '%vairogs.utils.lexik.translation.admin.orm.class%'
        public: true
        arguments:
            - ~
            - '%vairogs.utils.lexik.translation.admin.orm.entity%'
            - "@vairogs.utils.lexik.translation.crud.controller"
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: group.translation
                label_catalogue: LexikTranslationBundle
                label: translation.page_title
        calls:
            -
                - setTranslationDomain
                -
                    - 'LexikTranslationBundle'
                - setTransUnitManager
                -
                    - "@lexik_translation.trans_unit.manager"
                - setTemplate
                -
                    - 'list'
                    - '%vairogs.utils.lexik.translation.admin.orm.template%'
